FROM registry.access.redhat.com/ubi8/ubi:latest

ENV OCPVERSION="4.7.7"

ENV OCPRHCOSVERSION="4.7.0"

ENV HELPERNODEVERSION="v2beta"

RUN dnf -y install haproxy jq python3-pip && \
    python3 -m pip install -U pip && \
    pip3 install "ansible==2.9"

COPY files/haproxy.cfg.j2 /usr/local/src/

COPY scripts/startup.sh /usr/local/bin/

EXPOSE 9000/tcp 9000/udp 6443/tcp 6443/udp 22623/tcp 22623/udp 80/tcp 80/udp 443/tcp 443/udp

RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/haproxy

ENTRYPOINT ["/usr/local/bin/startup.sh"]
