FROM registry.access.redhat.com/ubi8/ubi:latest

ENV OCPVERSION="4.7.7"

ENV OCPRHCOSVERSION="4.7.0"

ENV HELPERNODEVERSION="v2beta"

COPY files/CentOS.repo /etc/yum.repos.d/

RUN chmod 0644 /etc/yum.repos.d/CentOS.repo && \
    dnf -y install --enablerepo CentOS-AppStream bind bind-utils && \
    dnf -y install jq python3-pip && \
    python3 -m pip install -U pip && \
    pip3 install "ansible==2.9"

COPY files/named.conf.j2 /usr/local/src/
COPY files/reverse.j2 /usr/local/src/
COPY files/zonefile.j2 /usr/local/src/

COPY scripts/startup.sh /usr/local/bin/

RUN rm -f /etc/yum.repos.d/CentOS.repo

EXPOSE 53/tcp 53/udp

ENTRYPOINT ["/usr/local/bin/startup.sh"]
