FROM registry.access.redhat.com/ubi8/ubi:latest

ENV OCPVERSION="4.6.4"

ENV OCPRHCOSVERSION="4.6.1"

ENV HELPERNODEVERSION="v2alpha1"

COPY files/CentOS.repo /etc/yum.repos.d/CentOS.repo

RUN chmod 0644 /etc/yum.repos.d/CentOS.repo && \
    dnf -y install --enablerepo CentOS-BaseOS dhcp-server && \
    dnf -y install jq python3-pip && \
    pip3 install ansible

COPY files/dhcpd.conf.j2 /usr/local/src/

COPY scripts/startup.sh /usr/local/bin/

EXPOSE 67/udp

RUN rm -f /etc/yum.repos.d/CentOS.repo

ENTRYPOINT ["/usr/local/bin/startup.sh"]
