---
# tasks file for configure-local-registry

- name: Create registry directories
  file:
    path: /opt/registry/{{ item }}
    state: directory
  with_items:
    - auth
    - certs
    - data

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  run_once: true
  openssl_privatekey:
    path: /opt/registry/certs/domain.pem

- name: Generate an OpenSSL Certificate Signing Request
  run_once: true
  openssl_csr:
    path: /opt/registry/certs/domain.csr
    privatekey_path: /opt/registry/certs/domain.pem
    basic_constraints:
      - CA:TRUE
    basic_constraints_critical: yes
    common_name: "{{ registry_host }}"

- name: Generate a Self Signed OpenSSL certificate
  run_once: true
  openssl_certificate:
    path: /opt/registry/certs/domain.crt
    privatekey_path: /opt/registry/certs/domain.pem
    csr_path: /opt/registry/certs/domain.csr
    provider: selfsigned

- name: Create the user and password for local registry
  run_once: true
  shell: htpasswd -bBc /opt/registry/auth/htpasswd {{ setup_registry.registry_user | default('admin') }} {{ setup_registry.registry_password | default('admin') }}
  args:
    creates: /opt/registry/auth/htpasswd

- name: Synchronize directories across all hosts
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    recursive: yes
  delegate_to: "{{ ansible_play_batch[0] }}"
  with_items:
    - /opt/registry/
    - ~/.openshift/
  when: high_availability is defined

- name: Copy Self Signed OpenSSL certificate
  copy:
    src: /opt/registry/certs/domain.crt
    dest: /etc/pki/ca-trust/source/anchors/domain.crt
    remote_src: yes
    force: yes

- name: Add the Self Signed OpenSSL certificate to your list of trusted certificates
  shell: |
    update-ca-trust || true
    cat /etc/pki/tls/certs/ca-bundle.trust.crt | grep {{ registry_host }} | wc -l
  register: cert_trust
  until: cert_trust.stdout|int == 1
  retries: 3
  delay: 10

- name: Downloading oc-mirror package
  get_url:
    url: "{{ oc_mirror }}"
    dest: /usr/local/src/oc-mirror.tar.gz
    mode: 0644
  when: download_imgs or force_ocp_download
  
- name: Unarchiving oc-mirror package
  unarchive:
    src: /usr/local/src/oc-mirror.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    creates: "{{ oc_mirror_bin }}"

- name: Set executable permission on oc-mirror
  file:
    path: "/usr/local/bin/{{ oc_mirror_bin }}"
    mode: "0755"
    owner: root
    group: root

- name: Get openshift-install architecture
  shell: |
    openshift-install version | awk '/architecture/ {print $3}'
  register: os_install_arch
  changed_when: false

- name: Set ImageSet architecture
  set_fact:
    imageset_arch: >-
      {{
        ['amd64', 'arm64', 'ppc64le', 's390x']
        if os_install_arch.stdout == 'multi'
        else
        [os_install_arch.stdout]
        if os_install_arch.rc == 0 and os_install_arch.stdout | length > 0
        else
        ['amd64']
      }}

- name: Copy ImageSetConfig file    
  template:
    src: ../templates/imageset-config.yaml.j2
    dest: /etc/imageset-config.yaml
    owner: root
    group: root
    mode: 0666

- name: Generate local-registry service file
  template:
    src: ../templates/local-registry.service.j2
    dest: /etc/systemd/system/local-registry.service
    mode: 0655

- name: Start local-registry
  systemd:
    name: local-registry
    state: started
    enabled: yes
    daemon_reload: yes

- name: Ensure registry pod is up
  shell: podman ps | grep local-registry
  register: pod_state
  until: pod_state.stdout != ""
  retries: 4
  delay: 15

- name: Allow traffic at local registry port
  firewalld:
    port: 5000/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: Restarting registry services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ registry_services }}"

- name: Get local registry pod
  shell: curl -u {{ setup_registry.registry_user | default('admin') }}:{{ setup_registry.registry_password | default('admin') }} -k https://{{ local_registry }}/v2/_catalog | grep repositories
  register: pod_state
  until: pod_state.stdout != ""
  retries: 3
  delay: 30

- name: Mirror the registry
  when: pod_state.stdout != ""
  block:
  - name: Generate the base64-encoded user name and password or token for your mirror registry
    shell: |
      registry_token=`echo -n "{{ setup_registry.registry_user  | default('admin') }}:{{ setup_registry.registry_password | default('admin') }}" | base64 -w0`
      jq '.auths += {"{{ local_registry }}": {"auth": "'$registry_token'","email": "noemail@localhost"}}' < ~/.openshift/pull-secret > ~/.openshift/pull-secret-updated
    args:
      creates: ~/.openshift/pull-secret-updated

  - name: Retrieve the Release Image Manifest
    shell: |
      oc adm release info {{ release_image }} -o json
    register: release_manifest

  - name: Query for the OCP Version from Release Image Manifest
    shell: |
      echo '{{ release_manifest.stdout }}' | jq -r '.' | jq -r '.config.config.Labels["io.openshift.release"]'
    register: release_version

  - name: Register the MAJOR, MINOR for the ocp_version
    shell: |
      echo "{{ release_version.stdout }}" | tr '.' ' ' | awk '{print $1, $2}'
    register: ocp_version

  - name: Check if image manifest is having Multi payload. 
    shell: |
      echo '{{ release_manifest.stdout }}' | jq -r '.metadata.metadata | ."release.openshift.io/architecture"?'
    register: multi_payload
  
  - name: Check if image manifest is having Single payload.
    shell: |
      RELEASE_DIGEST=$(oc image info --output=json -a ~/.openshift/pull-secret-updated {{ release_image }} | grep -c "Digest" )
      echo $RELEASE_DIGEST
    register: single_payload

  - name: Mirroring with multi arch payload 
    shell: |
      for DIGEST in $(oc image info --output=json -a ~/.openshift/pull-secret-updated {{ release_image }} 2>&1 | grep linux | awk '{print $NF}')
      do
        SIGFILE=$(echo $DIGEST | sed 's/:/-/g').sig
        oc image mirror -a ~/.openshift/pull-secret-updated \
          {{ setup_registry.remote_registry | default('quay.io') }}/{{ setup_registry.product_repo }}/{{ setup_registry.release_name }}:${SIGFILE} \ 
          {{ local_registry }}/{{ setup_registry.local_repo }}:${SIGFILE} \
          --force=false
      done
    register: multi_out
    when:
      - setup_registry.autosync_registry
      - multi_payload.stdout == "multi"
      - (((ocp_version.stdout.split(' ')[0] | int ) >= 4 and (ocp_version.stdout.split(' ')[1] | int) > 18 ) or ( (ocp_version.stdout.split(' ')[0] | int ) >= 5 ))

  - name: Mirroring with single arch payload
    shell: |
      CONTENT_DIGEST=$(oc image info --output=json -a ~/.openshift/pull-secret-updated {{ release_image }} \
        | jq -r '.contentDigest | split(":")[1]' )
      oc image mirror \
        -a ~/.openshift/pull-secret-updated \
        {{ setup_registry.remote_registry | default('quay.io') }}/{{ setup_registry.product_repo }}/{{ setup_registry.release_name }}:sha256-$CONTENT_DIGEST.sig \
        {{ local_registry }}/{{ setup_registry.local_repo }}:sha256-$CONTENT_DIGEST.sig \
        --force=false
    register: single_payload
    when:
      - setup_registry.autosync_registry
      - single_payload is defined
      - single_payload.stdout | trim | int != 0
      - (((ocp_version.stdout.split(' ')[0] | int ) >= 4 and (ocp_version.stdout.split(' ')[1] | int) > 18 ) or ((ocp_version.stdout.split(' ')[0] | int ) >= 5 ))

  - name: Mirror-to-mirror registry with oc-mirror v2
    shell: |
      oc-mirror --authfile /root/.openshift/pull-secret-updated \
        -c /usr/local/src/imageset-config.yaml \
        --workspace file://tmp/oc-mirror \
        docker://{{ local_registry }}/{{ setup_registry.local_repo }} \
        --secure-policy --v2 \
        --parallel-images {{ oc_mirror_parallel_images }} --parallel-layers {{ oc_mirror_parallel_layers }}
    register: ocmirror_result
    when:
      - setup_registry.autosync_registry
      - (((ocp_version.stdout.split(' ')[0] | int ) >= 4 and (ocp_version.stdout.split(' ')[1] | int) > 19 ) or ((ocp_version.stdout.split(' ')[0] | int ) >= 5 ))

  - name: Mirror the registry
    when: setup_registry.autosync_registry
    shell: oc adm -a ~/.openshift/pull-secret-updated release mirror \
      --from={{ release_image }} \
      --to={{ local_registry }}/{{ setup_registry.local_repo }} \
      --to-release-image={{ local_registry }}/{{ setup_registry.local_repo }}:{{ setup_registry.release_tag }}
    register: registry

  - name: Generate Local Registry information
    when: setup_registry.autosync_registry
    copy:
      content: "{{ registry.stdout }}"
      dest: ../postrun-local-registry-info

  - name: Process Local Registry information
    when: setup_registry.autosync_registry
    shell: "sed -i '1,/Success/d' ../postrun-local-registry-info"

  - name: Mirror NFS image (x86_64)
    when: setup_registry.autosync_registry and not ppc64le
    shell: |
      oc image mirror quay.io/external_storage/nfs-client-provisioner:latest registry.{{ dns.clusterid }}.{{ dns.domain }}:5000/nfs-client-provisioner:latest -a ~/.openshift/pull-secret-updated

  - name: Mirror NFS image (ppc64le)
    when: setup_registry.autosync_registry and ppc64le
    shell: "oc image mirror registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 registry.{{ dns.clusterid }}.{{ dns.domain }}:5000/nfs-client-provisioner:latest -a ~/.openshift/pull-secret-updated"
