---
# handlers file for tester
- name: restart bind
  service:
    name: named
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: restart tftp
  service:
    name: tftp
    state: restarted

- name: restart nfs
  service:
    name: nfs-server
    state: restarted

- name: Check postfix
  command: postfix check
  when: postfix_check